# custom keybindigs for MacOS

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt",   chars = "\u001bb"                       }, # skip word left
  { key = "Right", mods = "Alt",   chars = "\u001bf"                       }, # skip word right
  { key = "Left",  mods = "Super", chars = "\u001b[H", mode = "~AppCursor" }, # home
  { key = "Right", mods = "Super", chars = "\u001b[F", mode = "~AppCursor" }, # end
  { key = "Back",  mods = "Super", chars = "\u0015"                        }, # delete line
]
