#!/bin/bash

# ---------------------------------------------------------------------
# executes the bootstrap script for the specified hostname
# if the argument hostname is empty it will default to 'uname -n'
#     usage: bootstrap <hostname | uname -n>
# ---------------------------------------------------------------------

# checks arguments
[[ $# -gt 1 ]] && echo "Usage: bootstrap <hostname | uname -n>" && exit 1
HOSTNAME=${1:-$(uname -n)}
# checks if script exists
SCRIPT=$(dirname $(readlink -f $0))/bootstrap-${HOSTNAME}
[[ ! -f ${SCRIPT} ]] && echo "No bootstrap script for host: ${HOSTNAME}, ${SCRIPT} does not exist" && exit 1
# runs bootstrap-<hostname>
${SCRIPT}
