#!/bin/bash

# bootstraps custom scripts
. ${HOME}/.local/bin/tools/utils/symlinks/refresh-user-bin-links

# sets up this machine keys
setup-keys-from-yadm
# installs fonts
install-nerd-fonts Hack Ubuntu
# installs gnome extensions
install-extensions-from-file
# restores gnome properties
restore-dconf

# sets yadm repo to ssh
yadm remote set-url origin "git@github.com:PedroJoaoPereira/dotfiles.git"
